"""Map pain points to solution types and generate ready-to-run build briefs for Claude Code."""
from __future__ import annotations

import re
from collections import Counter
from typing import Any

from .models import PainPoint
from .text import snippet

# solution type -> (description, keyword regex, pain tags that favour it)
SOLUTION_TYPES: dict[str, tuple[str, str, set[str]]] = {
    "android_app": (
        "Native/mobile app (Kotlin/Jetpack Compose or React Native/Expo)",
        r"\b(phone|mobile|android|iphone|ios|on the go|notification|reminder|offline|camera|scan|gps|widget)\b",
        {"tool_seeking", "feature_gap"},
    ),
    "web_saas": (
        "Web app / micro-SaaS (Next.js + Postgres + Stripe)",
        r"\b(dashboard|track|manage|team|client|customer|schedule|booking|invoice|crm|portal|report|platform)\w*",
        {"tool_seeking", "alternative", "price", "willingness_to_pay"},
    ),
    "ai_tool": (
        "AI-powered tool / agent (Claude API)",
        r"\b(write|writing|generate|summar\w*|draft|translate|analy[sz]\w*|classif\w*|extract|chat|answer|ai|gpt|llm|research)\b",
        {"time_waste", "workaround", "tool_seeking"},
    ),
    "automation": (
        "Automation / integration (scripts, Zapier-style connectors, bots)",
        r"\b(automat\w*|manual\w*|spreadsheet|excel|sheets|copy.?paste|sync|import|export|csv|api|integrat\w*|repetitive)\b",
        {"workaround", "time_waste", "feature_gap"},
    ),
    "browser_extension": (
        "Browser extension (Chrome/Firefox)",
        r"\b(browser|chrome|firefox|tab|tabs|website|page|extension|linkedin|youtube|amazon|gmail)\b",
        {"feature_gap", "time_waste"},
    ),
    "content": (
        "Content product (YouTube series, course, newsletter, guide, templates)",
        r"\b(how to|learn|tutorial|guide|explain|beginner|confus\w*|understand|tips|advice|course|step by step|templates?|checklist|examples?)\b",
        {"how_to"},
    ),
    "marketplace_directory": (
        "Directory / comparison / marketplace site",
        r"\b(find|compare|comparison|recommend\w*|which (one|is best)|list of|directory|near me|hire|freelancer)\b",
        {"tool_seeking", "alternative"},
    ),
    "marketing_service": (
        "Done-for-you service or marketing play (agency, productized service)",
        r"\b(leads?|marketing|sales|clients?|customers?|grow|growth|seo|ads|social media|followers|outreach)\b",
        {"willingness_to_pay"},
    ),
}


def recommend(point: PainPoint, top_n: int = 3) -> list[dict[str, Any]]:
    corpus = " ".join(s.body.lower() for s in point.signals)[:60000]
    tags = Counter(point.tags)
    total = max(1, len(point.signals))
    scored = []
    for key, (desc, pattern, fav) in SOLUTION_TYPES.items():
        hits = len(re.findall(pattern, corpus))
        kw = min(1.0, hits / (total * 0.8 + 2))
        tag = min(1.0, sum(tags.get(t, 0) for t in fav) / total)
        s = 0.6 * kw + 0.4 * tag
        scored.append((s, key, desc, hits))
    scored.sort(reverse=True)
    out = []
    for s, key, desc, hits in scored[:top_n]:
        out.append({"type": key, "description": desc, "fit": round(min(1.0, s) * 100),
                    "keyword_hits": hits})
    return out


def build_brief(point: PainPoint, niche: str, rank: int) -> str:
    """A self-contained prompt you can hand straight to Claude Code (or a Hermes agent)."""
    llm = point.llm or {}
    name = llm.get("name") or point.label
    sol = (llm.get("solutions") or [None])[0]
    quotes = "\n".join(
        f'- [{s.source}{"/" + str(s.meta.get("subreddit")) if s.meta.get("subreddit") else ""}] '
        f'"{snippet(s.body, 240)}" ({int(s.score)} pts, {s.comments} comments) {s.url}'
        for s in point.top_quotes(8)
    )
    comp = point.components
    sol_lines = "\n".join(f"- **{x['type']}** (fit {x['fit']}): {x['description']}" for x in point.solutions)
    if sol:
        features = "\n".join(f"- {f}" for f in sol.get("mvp_features", []))
        product = (f"## Proposed product\n**{sol.get('name', '')}** ({sol.get('type', '')}): "
                   f"{sol.get('one_liner', '')}\n\nMVP features:\n{features}\n\n"
                   f"Monetization: {sol.get('monetization', 'n/a')}\n")
    else:
        product = ("## Proposed product\nPick the best-fitting solution type below, name the product, "
                   "and define the smallest MVP that removes this pain for the people quoted.\n")
    problem = llm.get("problem_statement") or (
        f"People in the '{niche}' space repeatedly complain about: {', '.join(point.keywords[:5])}.")
    who = llm.get("who") or "See evidence quotes; infer the user persona from them."
    return f"""# Build brief #{rank}: {name}

> Generated by demand-scanner for the niche **{niche}**.
> Demand score **{point.score:.0f}/100** across {len(point.signals)} signals from {', '.join(point.sources)}.

## The pain
{problem}

**Who has it:** {who}

Score breakdown: volume {comp.get('volume', 0):.2f} · engagement {comp.get('engagement', 0):.2f} ·
intensity {comp.get('intensity', 0):.2f} · willingness-to-pay {comp.get('wtp', 0):.2f} ·
solution-gap {comp.get('gap', 0):.2f} · breadth {comp.get('breadth', 0):.2f} · recency {comp.get('recency', 0):.2f}

Pain types detected: {', '.join(f'{k} ({v})' for k, v in point.tags.items()) or 'n/a'}

## Evidence (real quotes)
{quotes}

{product}
## Candidate solution types (heuristic ranking)
{sol_lines}

## Instructions for the coding agent
1. Read the evidence above and write a one-paragraph product spec in `SPEC.md` (user, job-to-be-done, MVP scope, non-goals).
2. Choose a stack appropriate for the solution type (default: Next.js + SQLite/Postgres for web, Kotlin + Jetpack Compose for Android, Claude API for AI features).
3. Scaffold the project, implement the MVP end-to-end, and add tests for the core flow.
4. Add a landing page / store listing copy that speaks directly to the quoted pain, using the users' own words.
5. Write `README.md` with setup, run, and deploy steps. Keep the MVP small enough to ship in a weekend.
"""
